### ISSUE TITLE
Unable to find Unknown EMESSAGE

### ISSUE THREAD

**Issue by luigystoro** [nftools/underscore#1]
Cuando compilo un programa donde se utiliza underscore me sale el siguiente mensaje

Unable to find Unknown EMESSAGE

He chequeado y EMESSAGE es una variable local de _.prg.

¿Cómo se puede solucionar?

--------------------------

When I compile a program where underscore is used I get the following message

Unable to find Unknown EMESSAGE

I have checked and EMESSAGE is a local variable of _.prg.

How can it be solved?

**Comment by nftools** [comment]
Hola emessage() es una función que no debió aparecer en esta versión. 
Ya está solucionado., por favor descarga el fuente actualizado.
______________________________________________________________________

Hi, emessage() is a function that should not appear in this version. 
It is fixed now, please download the updated source.
